version: "3.9"
services:
  postgres:
    container_name: "postgres"
    restart: "unless-stopped"
    image: "postgres:alpine"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "./data:/var/lib/postgresql/data"
  redis:
    container_name: "redis"
    restart: "unless-stopped"
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"
  awesomemy:
    container_name: "awesomemy"
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - "./config.yaml:/config.yaml"