// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/gobuffalo/nulls"
	"github.com/gofrs/uuid"
)

type Event struct {
	EventID     int32
	Uuid        uuid.UUID
	Name        string
	Description string
	StartsAt    time.Time
	EndsAt      time.Time
	CreatedAt   time.Time
	Website     nulls.String
	UserID      int32
	Slug        nulls.String
}

type EventTag struct {
	EventID int32
	TagID   int32
}

type Project struct {
	ProjectID   int32
	Uuid        uuid.UUID
	Name        string
	Description string
	UserID      int32
	CreatedAt   time.Time
	Repository  nulls.String
	Website     nulls.String
	Slug        nulls.String
}

type ProjectTag struct {
	ProjectID int32
	TagID     int32
}

type Tag struct {
	TagID int32
	Uuid  uuid.UUID
	Name  string
	Slug  nulls.String
}

type User struct {
	UserID      int32
	Uuid        uuid.UUID
	GithubEmail nulls.String
	CreatedAt   time.Time
	GoogleEmail nulls.String
}
